/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py:104: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @app.on_event("startup")
INFO:     Started server process [3199823]
INFO:     Waiting for application startup.
INFO:__main__:开始初始化STT模型...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_frontend.py", line 20, in <module>
    from funasr.auto.auto_model import prepare_data_iterator
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 35, in <module>
    from funasr.models.campplus.cluster_backend import ClusterBackend
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import pandas as pd
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_frontend.py", line 20, in <module>
    from funasr.auto.auto_model import prepare_data_iterator
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 35, in <module>
    from funasr.models.campplus.cluster_backend import ClusterBackend
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import pandas as pd
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_frontend.py", line 20, in <module>
    from funasr.auto.auto_model import prepare_data_iterator
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 35, in <module>
    from funasr.models.campplus.cluster_backend import ClusterBackend
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import pandas as pd
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 52, in <module>
    from pandas.core import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_frontend.py", line 20, in <module>
    from funasr.auto.auto_model import prepare_data_iterator
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 35, in <module>
    from funasr.models.campplus.cluster_backend import ClusterBackend
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import pandas as pd
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 66, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 61, in <module>
    from pandas.core import (
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_frontend.py", line 20, in <module>
    from funasr.auto.auto_model import prepare_data_iterator
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 35, in <module>
    from funasr.models.campplus.cluster_backend import ClusterBackend
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/metrics/compute_eer.py", line 2, in <module>
    from sklearn.metrics import roc_curve
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 20, in <module>
    from .utils._missing import is_scalar_nan
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/metrics/compute_eer.py", line 2, in <module>
    from sklearn.metrics import roc_curve
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 20, in <module>
    from .utils._missing import is_scalar_nan
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 20, in <module>
    from .utils._missing import is_scalar_nan
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 20, in <module>
    from .utils._missing import is_scalar_nan
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 20, in <module>
    from .utils._missing import is_scalar_nan
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/bygpu/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/home/bygpu/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bygpu/Documents/chat-stt-agent/fastapi_backend.py", line 84, in initialize_stt_model
    from funasr import AutoModel
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 37, in <module>
    import_submodules(__name__)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/__init__.py", line 27, in import_submodules
    results[name] = importlib.import_module(name)
  File "/home/bygpu/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/funasr/models/campplus/cluster_backend.py", line 9, in <module>
    import sklearn
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 20, in <module>
    from .utils._missing import is_scalar_nan
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 421, in <module>
    import pyarrow
  File "/home/bygpu/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
INFO:root:download models from model hub: ms
WARNING:root:trust_remote_code: True
INFO:root:Loading pretrained params from /home/bygpu/model/iic/SenseVoiceSmall/model.pt
INFO:root:ckpt: /home/bygpu/model/iic/SenseVoiceSmall/model.pt
INFO:root:scope_map: ['module.', 'None']
INFO:root:excludes: None
INFO:root:Loading ckpt: /home/bygpu/model/iic/SenseVoiceSmall/model.pt, status: <All keys matched successfully>
INFO:root:Building VAD model.
INFO:root:download models from model hub: ms
WARNING:root:trust_remote_code: False
INFO:root:Loading pretrained params from /home/bygpu/.cache/modelscope/hub/models/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
INFO:root:ckpt: /home/bygpu/.cache/modelscope/hub/models/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
INFO:root:scope_map: ['module.', 'None']
INFO:root:excludes: None
INFO:root:Loading ckpt: /home/bygpu/.cache/modelscope/hub/models/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt, status: <All keys matched successfully>
INFO:__main__:STT模型初始化成功！
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
